export const GET_ABOUT_DATA = 'about/GET_ABOUT_DATA';
export const GET_RECOMMENDATIONS_DATA = 'about/GET_RECOMMENDATIONS_DATA';
export const STORE_ABOUT_DATA = 'about/STORE_ABOUT_DATA';
export const STORE_RECOMMENDATIONS_DATA = 'about/STORE_RECOMMENDATIONS_DATA';
